In [13]:
import scipy.stats 
from scipy.stats import spearmanr
from scipy.stats import kendalltau
from numpy import corrcoef


In [9]:
spearmanr([1,2,3,4],[6,7,8,9]) ,\
spearmanr([1,3,-3,4],[6,7,-8,9]),\
spearmanr([1,3,-3,4],[6,7,8,9])

(SpearmanrResult(correlation=1.0, pvalue=0.0),
 SpearmanrResult(correlation=1.0, pvalue=0.0),
 SpearmanrResult(correlation=0.39999999999999997, pvalue=0.6))

In [11]:
kendalltau([1,2,3,4],[6,7,8,9]) ,\
kendalltau([1,3,-3,4],[6,7,-8,9]),\
kendalltau([1,3,-3,4],[6,7,8,9])

(KendalltauResult(correlation=1.0, pvalue=0.08333333333333333),
 KendalltauResult(correlation=1.0, pvalue=0.08333333333333333),
 KendalltauResult(correlation=0.3333333333333334, pvalue=0.75))

In [14]:
corrcoef([1,2,3,4],[6,7,8,9]) ,\
corrcoef([1,3,-3,4],[6,7,-8,9]),\
corrcoef([1,3,-3,4],[6,7,8,9])

(array([[1., 1.],
        [1., 1.]]),
 array([[1.        , 0.96344426],
        [0.96344426, 1.        ]]),
 array([[1.        , 0.12510865],
        [0.12510865, 1.        ]]))

In [17]:
corrcoef([[1,2,3],[3,4,-5]])

array([[ 1.        , -0.81088485],
       [-0.81088485,  1.        ]])